name: deploy firebase
on:
  push:
    branches:
      - "master"
      - "actions/deploy-firebase__*"
jobs:
  deploy:
    name: deploy firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.8"
          channel: "stable"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"
      - name: enable Flutter web
        run: flutter channel dev && flutter config --enable-web
      - name: install yarn
        run: npm install -g yarn@latest
      - name: install firebase CLI
        run: npm install -g firebase-tools@latest
      - name: install functions dependencies
        working-directory: functions
        run: npm install
      - name: install docs dependencies
        working-directory: docs
        run: yarn install
      - name: install app dependencies
        working-directory: app
        run: flutter pub get
      - name: build docs
        working-directory: docs
        run: yarn docs:build
      - name: build web app
        working-directory: app
        run: flutter build web
      - name: deploy firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN
